<?php

    require "../
    conexion.php";

    if ($_SERVER['REQUEST_METHOD'] == 'PUT'){

        $ID_PERSONAJE = $_GET['ID_PERSONAJE'];
        $NOMBRE_PERSONAJE = $_GET ['NOMBRE_PERSONAJE'];
        $APELLIDO_PERSONAJE = $_GET ['APELLIDO_PERSONAJE'];
        $FECHA_NACIMIENTO_PERSONAJE = $_GET ['FECHA_NACIMIENTO_PERSONAJE'];
        $RAZA_PERSONAJE = $_GET ['RAZA_PERSONAJE'];
        $PAPEL_PERSONAJE = $_GET ['PAPEL_PERSONAJE'];
        $FOTO_PERSONAJE = $_GET ['FOTO_PERSONAJE'];
        $ACTOR_PERSONAJE = $_GET ['ACTOR_PERSONAJE'];
        
        $sql = "UPDATE personaje SET NOMBRE_PERSONAJE='$NOMBRE_PERSONAJE', APELLIDO_PERSONAJE='$APELLIDO_PERSONAJE', FECHA_NACIMIENTO_PERSONAJE='$FECHA_NACIMIENTO_PERSONAJE', RAZA_PERSONAJE='$RAZA_PERSONAJE', PAPEL_PERSONAJE='$SINOPSIS_PELICULA, FOTO_PERSONAJE='$FOTO_PERSONAJE', ACTOR_PERSONAJE='$ACTOR_PERSONAJE' WHERE ID_PERSONAJE='$ID_PERSONAJE'";
        
        $query = $mysqli->query($sql);
        echo "Personaje actualizado correctamente";
    }else{
        header("HTTP/1.1 501 Not Implemented");
        echo "Error de metodo";
    }

?>
